export const enum Technology {
    JS = "JavaScript",
    TS = "TS",
    NODE = "Node",
    HTML = "HTML",
    CSS = "CSS",
    AWS = "AWS",
    GCP = "GCP",
    WEBPACK = "Webpack",
    CRYPTO = "Crypto",
    IOT = "IOT",
    FULL_STACK = "Full Stack",
    ANGULAR = "Angular",
    REACT = "React",
    REDUX = "Redux",
    REDUX_FORM = "Redux Form",
    MATERIAL_UI = "material ui",
    CSS_MODULES = "CSS Modules",
    MONGO_DB = "MongoDB",
    JQUERY = "jQuery",
    DOCKER = "Docker",
    KUBERNETES = "Kubernetes"
}
